/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registrarJugadorMVC;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import registrarJugadorMVC.IModeloRegistro;

/**
 *
 * @author user
 */
public class VistaRegistro extends javax.swing.JFrame implements ObservadorRegistro {

    ControladorRegistro controladorRegistro;

    public VistaRegistro(ControladorRegistro controladorRegistro) {
        initComponents();
        this.controladorRegistro = controladorRegistro;
        this.cbAvatars.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizarAvatarSeleccionado();
            }
        });
    }

    public void actualizarAvatarSeleccionado() {
        if (cbAvatars.getSelectedItem() != null) {
            ImageIcon avatar = (ImageIcon) cbAvatars.getSelectedItem();
            controladorRegistro.seleccionarAvatar(avatar.getDescription());
        }
    }

    public void actualizarColorFicha(int index, Color color) {
        if (color != null) {
            controladorRegistro.seleccionarColorFicha(index, color);
        }
    }

    @Override
    public void actualizar(IModeloRegistro modeloRegistro) {
        if (!modeloRegistro.getVisible()) {
            DefaultComboBoxModel<ImageIcon> model = new DefaultComboBoxModel<>(modeloRegistro.getListaAvatars().toArray(new ImageIcon[0]));
            cbAvatars.setModel(model);
        }

        this.setVisible(modeloRegistro.getVisible());

        if (cbAvatars.getSelectedItem() != null && modeloRegistro.getRutaAvatarAgrandado() != null) {
            lblAvatar.setIcon(new ImageIcon(getClass().getResource(modeloRegistro.getRutaAvatarAgrandado())));
            lblAvatar.repaint();
        }
        System.out.println(modeloRegistro.getColores());
        btnFicha1.setForeground(modeloRegistro.getColores().get(0));
        btnFicha2.setForeground(modeloRegistro.getColores().get(1));
        btnFicha3.setForeground(modeloRegistro.getColores().get(2));
        btnFicha4.setForeground(modeloRegistro.getColores().get(3));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        cbAvatars = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnColorFicha1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnColorFicha2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnColorFicha3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnColorFicha4 = new javax.swing.JButton();
        btnFicha1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnFicha2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnFicha3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnFicha4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("Registrar Jugador");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Escoger Colores");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnColorFicha1.setText("Elegir");
        btnColorFicha1.setMaximumSize(new java.awt.Dimension(75, 23));
        btnColorFicha1.setPreferredSize(new java.awt.Dimension(75, 23));
        btnColorFicha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorFicha1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnColorFicha1);

        jLabel9.setText("  ");
        jPanel2.add(jLabel9);

        btnColorFicha2.setText("Elegir");
        btnColorFicha2.setPreferredSize(new java.awt.Dimension(75, 23));
        btnColorFicha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorFicha2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnColorFicha2);

        jLabel8.setText("  ");
        jPanel2.add(jLabel8);

        btnColorFicha3.setText("Elegir");
        btnColorFicha3.setPreferredSize(new java.awt.Dimension(75, 23));
        btnColorFicha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorFicha3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnColorFicha3);

        jLabel5.setText("  ");
        jPanel2.add(jLabel5);

        btnColorFicha4.setText("Elegir");
        btnColorFicha4.setPreferredSize(new java.awt.Dimension(75, 23));
        btnColorFicha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorFicha4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnColorFicha4);

        btnFicha1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFicha1.setText("10");
        btnFicha1.setPreferredSize(new java.awt.Dimension(75, 100));
        btnFicha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnFicha1);

        jLabel10.setText("  ");
        jPanel2.add(jLabel10);

        btnFicha2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFicha2.setForeground(new java.awt.Color(255, 51, 51));
        btnFicha2.setText("10");
        btnFicha2.setPreferredSize(new java.awt.Dimension(75, 100));
        jPanel2.add(btnFicha2);

        jLabel7.setText("  ");
        jPanel2.add(jLabel7);

        btnFicha3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFicha3.setForeground(new java.awt.Color(51, 255, 0));
        btnFicha3.setText("10");
        btnFicha3.setPreferredSize(new java.awt.Dimension(75, 100));
        jPanel2.add(btnFicha3);

        jLabel6.setText("  ");
        jPanel2.add(jLabel6);

        btnFicha4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFicha4.setForeground(new java.awt.Color(0, 51, 255));
        btnFicha4.setText("10");
        btnFicha4.setPreferredSize(new java.awt.Dimension(75, 100));
        jPanel2.add(btnFicha4);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Avatar");

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatars/knight2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbAvatars, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(225, 225, 225)
                    .addComponent(jLabel4)
                    .addContainerGap(988, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbAvatars, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblAvatar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(243, 243, 243)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(439, 439, 439)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        controladorRegistro.seleccionarNombre(txtNombre.getText());
        controladorRegistro.registrarJugador();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnColorFicha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorFicha1ActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        Color color = JColorChooser.showDialog(null, "Escoge un Color", btnFicha1.getForeground());
        this.actualizarColorFicha(0, color);
    }//GEN-LAST:event_btnColorFicha1ActionPerformed

    private void btnColorFicha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorFicha2ActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        Color color = JColorChooser.showDialog(null, "Escoge un Color", btnFicha2.getForeground());
        this.actualizarColorFicha(1, color);

    }//GEN-LAST:event_btnColorFicha2ActionPerformed

    private void btnColorFicha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorFicha3ActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        Color color = JColorChooser.showDialog(null, "Escoge un Color", btnFicha3.getForeground());
        this.actualizarColorFicha(2, color);
    }//GEN-LAST:event_btnColorFicha3ActionPerformed

    private void btnColorFicha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorFicha4ActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        Color color = JColorChooser.showDialog(null, "Escoge un Color", btnFicha4.getForeground());
        this.actualizarColorFicha(3, color);
    }//GEN-LAST:event_btnColorFicha4ActionPerformed

    private void btnFicha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFicha1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorFicha1;
    private javax.swing.JButton btnColorFicha2;
    private javax.swing.JButton btnColorFicha3;
    private javax.swing.JButton btnColorFicha4;
    private javax.swing.JButton btnFicha1;
    private javax.swing.JButton btnFicha2;
    private javax.swing.JButton btnFicha3;
    private javax.swing.JButton btnFicha4;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<ImageIcon> cbAvatars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMensaje(String mensaje) {
    JOptionPane.showMessageDialog(this, mensaje, "Notificacion", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void mostrarError(String mensaje) {
    JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

}
